config/routes.rb
Mockshare::Application.routes.draw do
  resources :cards

  devise_for :users

  get 'about' => "pages#about"

  root :to => 'cards#index'

end

app/models/card.rb
require 'open-uri'

class Card < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url
  has_attached_file :image

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
                               content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                               size: { less_than: 5.megabytes }

  belongs_to :user
  has_attached_file :image, styles: { :thumb => "100x100#",
                                      :small  => "150x150>",
                                      :square => "250x250>",
                                      :medium => "300x300>"  }
  # Needed for remote_url
  attr_accessor :image_remote_url

  before_validation :download_remote_image, :if => :image_url_provided?

  validates_presence_of :image_remote_url, :if => :image_url_provided?, :message => 'is invalid or inaccessible'

private
# They are not accessible to everyone else

  def image_url_provided?
    !self.image_remote_url.blank?
  end

  def download_remote_image
    self.image = do_download_remote_image
    self.image_remote_url = image_remote_url
  end

  def do_download_remote_image
    io = open(URI.parse(image_url))
    def io.original_filename; base_uri.path.split('/').last; end
    io.original_filename.blank? ? nil : io
  rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :cards, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = current_user.cards.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = current_user.cards.find(params[:id])
    #Change refer to cards by the current user
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = current_user.cards.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = current_user.cards.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = current_user.cards.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_card.html.erb
<div class="box">
  <%= link_to (image_tag card.image.url(:square)), card %>
  <p class="description">
    <%= card.description %>
  </p>
  <p><strong>Posted by <%= card.user.name %></strong></p>
  <%= link_to 'Show', card %>
  <% if current_user == card.user %>
  <!-- Only show if logged in user created the card -->
    <p>
      <%= link_to 'Edit', edit_card_path(card) %>
      <%= link_to 'Delete', card, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

app/views/cards/_form.html.erb
<%= simple_form_for(@card, html: { class: "form-horizontal" }) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
<!--   <%= f.input :image_remote_url, label: "..or provide a URL: " %>
 -->
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="well well-large">

  <h1>Editing card</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @card %> |
  <%= link_to 'Back', cards_path %>

</div>

app/views/cards/index.html.erb
<%= render 'pages/home' %>

<div id="cards">

  <%= render @cards %>

</div>

app/views/cards/new.html.erb
<div class="well well-large">

  <h1>New card</h1>

  <%= render 'form' %>

  <%= link_to 'Back', cards_path %>

</div>

app/views/cards/show.html.erb
<div class="row">
  <div class="span6 offset2">
    <div class="well">
      <div class="show_solo">
        <%= image_tag @card.image.url(:medium) %>
        <p>
          <%= @card.description %>
        </p>
        <p>
          By: <%= @card.user.name %>
        </p>
        <p>
        <% if current_user == @card.user %>
          <%= link_to 'Edit', edit_card_path(@card) %> |
        <% end %>
          <%= link_to 'Back', cards_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    Created by <%= link_to "Drew Butler", "http://www.butlerandrew.com" %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

		<%= link_to "Mockshare", root_path, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav pull-right">
		  	<% if user_signed_in? %>
			 <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
       <li><%= link_to 'New Mockup', new_card_path %></li>
       <li><%= link_to "View my Mockups", cards_path %></li>
		    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
			<% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
         <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Mockshare</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
    </head>
    <body>
      <%= render 'layouts/header' %>

      <div class="container">
        <% flash.each do |name, msg| %>
		  		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		  <% end %>
		  <%= yield %>
        <div class="clear"></div>
        <%= render 'layouts/footer' %>
      </div>

    </body>
  </html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
	<div class="hero-unit">
	   <h1>Welcome back</h1>
	   <p>Got a picture to add?</p>
		 <p><%= link_to "Add a Mockup", new_card_path, class: "btn btn-primary btn-large" %></a>
    <%= link_to "View my Mockups", cards_path, class: "btn btn-primary btn-large" %></a></p>
	</div>
<% else %>
	<div class="hero-unit">
  		<h1>Welcome to Mockshare</h1>
  		<p>Share your mockups with the world</p>
  		<p><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %></a></p>
	</div>
<% end %>

app/views/pages/about.html.erb
<div class="well well-large">
  <h1>About</h1>

  <p><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary" %></p>
  <p>Mockshare is a web service to allow users to share their mockups of websites, mobile apps, and other mockups they want to share with the world.</p>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="hero-unit">
	   <h1>Welcome back</h1>
	   <p>Got a picture to add?</p>
		 <p><%= link_to "Add a Mockup", new_card_path, class: "btn btn-primary btn-large" %></a>
    <%= link_to "View my Mockups", cards_path, class: "btn btn-primary btn-large" %></a></p>
	</div>
<% else %>
	<div class="hero-unit">
  		<h1>Welcome to Mockshare</h1>
  		<p>Share your mockups with the world</p>
  		<p><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %></a></p>
	</div>
<% end %>